global:
  scrape_interval:     10s
  evaluation_interval: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
  - "./rules/instance_rules.yaml"

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['192.168.199.11:9100', '192.168.199.12:9100', '192.168.199.13:9100', '192.168.199.14:9100', '192.168.199.15:9100', '192.168.199.21:9100']

  - job_name: 'Kube-state-metrics'
    static_configs:
    - targets: ['metrics.acme-wordpress.rooter.se']