# Values to be injected into the acme wordpress platform umbrella chart.
# Namespace = acme
# Use this file to specify namespace-specific values.
# Enable/disable services by setting the "enabled" flag.

resources: {}

wordpress:
  nameOverride: wordpress
  fullnameOverride: wordpress
  image:
    registry: docker.io
    repository: brocahontaz/acme_wordpress
    tag: latest
    pullPolicy: Always
  wordpressUsername: admin
  wordpressPassword: supersecretpassword123
  wordpressEmail: johan@rooter.se
  wordpressFirstName: Johan
  wordpressLastName: Andersson
  wordpressBlogName: ACME
  wordpressSkipInstall: true
  replicaCount: 5
  htaccessPersistenceEnabled: yes
  service:
    type: ClusterIP
    externalTrafficPolicy: Cluster
  ingress: 
    enabled: true
    certManager: false
    hostname: "acme-kevin.rooter.se"
    annotations: 
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    tls: false
    extraHosts:
      - name: "acme-kevin.rooter.se"
        path: /
    extraTls:
      - hosts:
          - acme-kevin.rooter.se
        secretName: acme-kevin.rooter.se-tls
  persistence:
    enabled: true
    storageClass: nfs
    accesMode: ReadWriteMany
    size: 8G
  mariadb:
    enabled: true
    image:
      registry: docker.io
      repository: brocahontaz/acme_mariadb
      tag: latest
    replication:
      enabled: true
    db:
      rootUser:
        password: supersecretpassword123
    master:
      persistence: 
        enabled: true
        storageClass: nfs
        accessModes: [ReadWriteOnce]
        size: 8G
    slave:
      persistence: 
        enabled: true
        storageClass: nfs
        accessModes: [ReadWriteOnce]
        size: 8G
    volumePermissions:
      enabled: true
    auth:
      rootPassword: supersecretpassword123