# Values to be injected into the acme wordpress platform umbrella chart.
# Namespace = acme
# Use this file to specify namespace-specific values.
# Enable/disable services by setting the "enabled" flag.

resources: {}

# ---Ingress resource for routing and certificates---
#
# Set production flag to true to use real certificates from letsencrypt.
# Otherwise letsencrypt staging server will be used.
ingress:
  enabled: true
  production: false
  spec:
    hosts:
      - control-panel: 
          hostName: cscloud7-61.lnu.se
          secretName: acme-wordpress-cert
          serviceName: wordpress
          servicePort: 80

# ---Internal services---

wordpress:
  nameOverride: wordpress
  fullnameOverride: wordpress
  wordpressUsername: admin
  wordpressPassword: supersecretpassword123
  wordpressEmail: johan@rooter.se
  wordpressFirstName: Johan
  wordpressLastName: Andersson
  wordpressBlogName: ACME
  replicaCount: 3
  service:
    type: ClusterIP
  persistence:
    enabled: true
    storageClass: sql-gold
    accesMode: ReadWriteOnce
    size: 8G
  mariadb:
    enabled: true
    db:
      name: acme
      user: admin
      password: supersecretpassword123
      rootUser:
        password: supersecretpassword123
    master:
      persistence: 
        enabled: true
        storageClass: sql-gold
        #accessModes: ReadWriteOnce
        size: 8G


# ---External services---

nginx-ingress-controller:
  replicaCount: 1
  service: 
    type: LoadBalancer
    loadBalancerIP: 194.47.177.61
    externalTrafficPolicy: "Cluster"