# Values to be injected into the acme wordpress platform umbrella chart.
# Namespace = acme
# Use this file to specify namespace-specific values.
# Enable/disable services by setting the "enabled" flag.

resources: {}

# ---Ingress resource for routing and certificates---
#
# Set production flag to true to use real certificates from letsencrypt.
# Otherwise letsencrypt staging server will be used.
ingress:
  enabled: false
  production: false
  spec:
    hosts:
      #- wordpress: 
      #    hostName: acme-wordpress.rooter.se
      #    secretName: acme-wordpress-cert
      #    serviceName: wordpress
      #    servicePort: 80
      #- nodetest:
      #    hostName: nodetest.rooter.se
      #    secretName: nodetest-cert
      #    serviceName: nodetest
      #    servicePort: 80


# ---Internal services---

wordpress:
  nameOverride: wordpress
  fullnameOverride: wordpress
  image:
    registry: docker.io
    repository: brocahontaz/acme_wordpress
    tag: latest
    pullPolicy: Always
  wordpressUsername: admin
  wordpressPassword: supersecretpassword123
  wordpressEmail: johan@rooter.se
  wordpressFirstName: Johan
  wordpressLastName: Andersson
  wordpressBlogName: ACME
  wordpressSkipInstall: true
  #wordpressScheme: https
  replicaCount: 5
  #allowOverrideNone: yes
  htaccessPersistenceEnabled: yes
  #securityContext:
  #  enabled: true
  #  runAsUser: 0
  #  fsGroup: 0
  service:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    #loadBalancerIP: 194.47.177.61
  ingress: 
    enabled: true
    certManager: false
    hostname: "acme-wordpress.rooter.se"
    annotations: 
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    tls: false
    extraHosts:
      - name: "acme-wordpress.rooter.se"
        path: /
    extraTls:
      - hosts:
          - acme-wordpress.rooter.se
        secretName: acme-wordpress.rooter.se-tls
  persistence:
    enabled: true
    storageClass: nfs
    accesMode: ReadWriteMany
    size: 8G
  mariadb:
    enabled: true
    image:
      registry: docker.io
      repository: brocahontaz/acme_mariadb
      tag: latest
    replication:
      enabled: true
    db:
      #name: acme
      #user: admin
      #password: supersecretpassword123
      rootUser:
        password: supersecretpassword123
    master:
      persistence: 
        enabled: true
        storageClass: nfs
        accessModes: [ReadWriteOnce]
        size: 8G
    slave:
      persistence: 
        enabled: true
        storageClass: nfs
        accessModes: [ReadWriteOnce]
        size: 8G
    volumePermissions:
      enabled: true
    auth:
      rootPassword: supersecretpassword123

# ---External services---

#nginx-ingress-controller:
#  replicaCount: 1
#  service: 
#    type: LoadBalancer
#    loadBalancerIP: 194.47.177.61
#    externalTrafficPolicy: Cluster