---
- name: Install docker
  include: docker.yaml

- name: Add developers keys to authorized_keys
  authorized_key:
    user: "{{ansible_user_id}}"
    state: present
    key: "{{ lookup('file', 'authorized_keys') }}"