global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: gabriel.bjorlin2@gmail.com
    from: gabriel.bjorlin2@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "gabriel.bjorlin2@gmail.com"
    auth_identity: "gabriel.bjorlin2@gmail.com"
    auth_password: "eg5mZD%*y#ve1WS95*hk#XOLJ85&iN34gWWcT&"
