kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sql-gold
provisioner: cinder.csi.openstack.org
parameters:
  availability: nova
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate