kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wp-gold
provisioner: cinder.csi.openstack.org
parameters:
  availability: nova
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate