- name: Init checks
  hosts: all
  gather_facts: no
  tasks:
  - name: Waiting for hosts to go online (240s timeout)
    wait_for_connection:
      timeout: 240

- name: "Role: monitoring"
  hosts: all
  roles:
    - monitoring
  tags:
    - monitoring