---

- hosts: all
  become: true
  tasks:

  - name: download node_exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
      dest: ./

  - name: unpack node_exporter
    shell: | 
      tar -xzf node_exporter-1.0.1.linux-amd64.tar.gz
      mv node_exporter-1.0.1.linux-amd64 node_exporter

  - name: run node_exporter
    shell: |
      cd ./node_exporter
      ./node_exporter #OBS: will freez
