{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  labels:
    {{- include "wordpress-platform.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{ include "issuer" . }}
spec:
  tls:
    {{- range .Values.ingress.spec.hosts }}
    {{- range . }}
    - hosts:
      - {{ .hostName }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
  rules:
  {{- range .Values.ingress.spec.hosts }}
  {{- range .}}
    - host: {{ .hostName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
  {{- end }}
  {{- end }}
{{- end }}